name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or update to '20' if necessary

      - name: Install SSH dependencies
        run: sudo apt-get install -y sshpass

      - name: Deploy to VM
        env:
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          sshpass -p "$VM_PASSWORD" ssh -o StrictHostKeyChecking=no $VM_USERNAME@207.148.122.61 << 'EOF'
            cd ~/flaskapp
            git pull origin master
            # Optional: Install dependencies or restart services
            # Example for a Python Flask application:
            # source venv/bin/activate
            # pip install -r requirements.txt
            # sudo systemctl restart your-service
            exit
          EOF
