name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y sshpass
          pip install pytest  

      # - name: Run tests
      #   run: pytest  # Run pytest after installation

      - name: Deploy to VM
        env:
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          sshpass -p "$VM_PASSWORD" ssh -o StrictHostKeyChecking=no $VM_USERNAME@207.148.122.61 << 'EOF'
            cd ~/flaskapp
            git pull origin main
            # Activate virtual environment (if you have one)
            # source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Stop the currently running Flask app if any (optional)
            pkill -f "python app.py" || true

            # Start the Flask app (replace with gunicorn for production)
            nohup python app.py > flaskapp.log 2>&1 &

            exit
          EOF
